script:
- echo "This is Daves Mondo module 9 work"
- echo "---------------------------------"
- FLASK_APP=todo_app/app
- FLASK_ENV=development
- docker build --target test --tag todoapptest .
- docker run -p 5000:5000 todoapptest
- docker build --target production -f Dockerfile --tag $DOCKERHUB_USERNAME/todoapp
  .
- echo $dockerhub_password | docker login --username $DOCKERHUB_USERNAME --password-stdin
- echo "Now for the push"
- echo "-------------------"
- docker push $DOCKERHUB_USERNAME/todoapp
- docker pull britboy4321/todoapp
- docker tag britboy4321/todoapp registry.heroku.com/todoappbritboy/web
- docker login --username=drawlinson48@gmail.com --password=$Heroku_finalpass2 registry.heroku.com
- docker push registry.heroku.com/todoappbritboy/web
- echo "CONTINUOUS DEPLOYMENT SETUP COMPLETED NOW"
- echo "-----------------------------------------"
- echo "TIME FOR ACTUAL DEPLOY and RELEASE NOW"
- echo "--------------------------------------"
deploy:
  provider: script
  script: heroku container:release web --app todoappbritboy
  on:
    branch: module9
  api_key:
    secure: C3Sh6zZbyXmaCfl/DnW8ySTtHQhCJ2RYUgWGtG+oNgfVowJTGVbtSoMGXbNsWKZt/vWBe0ToeG/4nWUEs8Eq7TnWKQI0zak2+elDKUCXJsKPyKW7xIZ1rVHvy/7wNfQDgVrs6NX4USSdqL8oiFWh3GOBcA2lca1cIxxWXi6QAMXt+CsHqPg9vOdIliZpefZUICzrJhFomx0CIOVjrDUwbaN3aVZeFmgMde/wngF0Hg1VSRqaTl8Rd0RZHm6/3haqrMKhXtZLqobbMJsa2uRLhhI1j5QG0Ey4GybuBfubvxiCtzispRvjKKX9fLJiYC8BrD0IrDszpQDRe2c1r8Sa/ItXZOKsPp5oKm0N29pzlKFPV9No+3gE3noAYAQ4NFkZzykRIHCEDilfw2EPNLeNbSDUcKp6lzEuOp5j8VDCjMS1JHljrjEYYxQ16QSX+xF9KMSzc62l/kj/146Q03LHXqiMgu0o/EGWvVbMPZdyJjE+4TENk8AfrsfcVZMIEWd3Qs0WiRalp6bxh2/dSKSzrMLJPHfwY84HLT+t0D2zErBsc0/HkLj0/ldmGeIEiPU2EQaSEDQaH21MbzaDzOpZhzNINflzTCwcH5GJHU86XN/A7crZnKdAvY1F+1q+k6kCyULeekvol30sIg9JIwR0pb1I123AI0afxIlCbHMdCQA=
