script:
- echo "This is Daves Mondo module 9 work again"
- echo "---------------------------------"
- FLASK_APP=todo_app/app
- FLASK_ENV=development
- docker build --target test --tag todoapptest .
- docker run -p 5000:5000 todoapptest
- docker build --target production -f Dockerfile --tag $DOCKERHUB_USERNAME/todoapp
  .
- echo $dockerhub_password | docker login --username $DOCKERHUB_USERNAME --password-stdin
- echo "Now for the push"
- echo "-------------------"
- docker push $DOCKERHUB_USERNAME/todoapp
- docker pull britboy4321/todoapp
- docker tag britboy4321/todoapp registry.heroku.com/todoappbritboy/web
- docker login --username=drawlinson48@gmail.com --password=$Heroku_finalpass2 registry.heroku.com
- docker push registry.heroku.com/todoappbritboy/web
- echo "CONTINUOUS DEPLOYMENT SETUP COMPLETED NOW"
- echo "-----------------------------------------"
- echo "TIME FOR ACTUAL DEPLOY and RELEASE NOW"
- echo "--------------------------------------"
deploy:
  provider: script
  script: heroku container:release web --app todoappbritboy
  on:
    branch: module9
  