script:
- echo "This is Daves Mondo module 9 work"
- echo "---------------------------------"
- FLASK_APP=todo_app/app
- FLASK_ENV=development
- docker build --target test --tag todoapptest .
- docker run -p 5000:5000 todoapptest
- docker build --target production -f Dockerfile --tag $DOCKERHUB_USERNAME/todoapp
  .
- echo $dockerhub_password | docker login --username $DOCKERHUB_USERNAME --password-stdin
- echo "Now for the push"
- echo "-------------------"
- docker push $DOCKERHUB_USERNAME/todoapp
- docker pull britboy4321/todoapp
- docker tag britboy4321/todoapp registry.heroku.com/todoappbritboy/web
- docker login --username=drawlinson48@gmail.com --password=$Heroku_finalpass2 registry.heroku.com
- docker push registry.heroku.com/todoappbritboy/web
- echo "CONTINUOUS DEPLOYMENT SETUP COMPLETED NOW"
- echo "-----------------------------------------"
- echo "TIME FOR ACTUAL DEPLOY and RELEASE NOW"
- echo "--------------------------------------"
deploy:
  provider: script
  script: heroku container:release web --app todoappbritboy
  on:
    branch: module9
  api_key:
    secure: OXYkGwqTfwU4oeUK/4Ui2tLGEN5no4rF7HsDj0Z9BCZOApAdYj5ItmrL3kL1OeU1YIEqOsCv1E9qxpkLdfMuPK566GKJWnHaqm5LHk2EqMAIutTFAwS9cvIDoPrKG6EjJCeH8bYYain4dq53VosWkspsKzVpVSVIQ731C3+Eq1NxO1iPD2AdQxsJerRSikV+oOnIabGnxrJ6rJPlJJxjvnEOUC6pATbolYFNwx96fHRJH2hFFDZM+oH1O2K+1VKnPJBavDuRyqftsLRjxpeEPLSIDpyUjI90v5xtW168sPCJZ/T1zOeNzziyA+VZKTWMNfCs0hv0P7J5ERZHwJarDVQnh/0dvKLuU2O5iL13mSmOxJS2eZmow8jxvdh4hqpJY/YHpEvlUSmFkzSq/jyUYlrm5W9XrUQaw/NB7CGSBTJ/fvCfhLKxgzT5vBFKaX5aOTSFj/gUgHYIMfRBmeKwFd/jCNYMRZCaIP+P8zzDDodzBGJKjxBErWjHou7j9g2U47LWkZrQRQxnbN4RvqZIn0hSRZ+4Xc/IEhspmBnOpgmPPuLKpFRp9ikiK2sM9jmCDFg6itjWufaYBFjSVXyq7SZRYq5MNIo6y14IyHbQsUxQV1UgWAfBWcVNlBiwMccS+dyrLpK01BsGGGidP0Y8a5u7WckubGOtYQRImVEgtGc=
