script:
- echo "This is Daves Mondo module 9 work"
- echo "---------------------------------"
- FLASK_APP=todo_app/app
- FLASK_ENV=development
- docker build --target test --tag todoapptest .
- docker run -p 5000:5000 todoapptest
- docker build --target production -f Dockerfile --tag $DOCKERHUB_USERNAME/todoapp
  .
- echo $dockerhub_password | docker login --username $DOCKERHUB_USERNAME --password-stdin
- echo "Now for the push"
- echo "-------------------"
- docker push $DOCKERHUB_USERNAME/todoapp
- docker pull britboy4321/todoapp
- docker tag britboy4321/todoapp registry.heroku.com/todoappbritboy/web
- docker login --username=drawlinson48@gmail.com --password=$Heroku_finalpass2 registry.heroku.com
- docker push registry.heroku.com/todoappbritboy/web
- echo "CONTINUOUS DEPLOYMENT SETUP COMPLETED NOW"
- echo "-----------------------------------------"
- echo "TIME FOR ACTUAL DEPLOY and RELEASE NOW"
- echo "--------------------------------------"
deploy:
  provider: script
  script: heroku container:release web --app todoappbritboy
  on:
    branch: module9
  api_key:
    secure: r1y48MjWW7Waxd4Up82kmC9CJbNmjatNzOAWLq8EZjkNFCMyAFeLSgnHDFe0Ki13TvVRXaHT/T3V9FSfrGJBfiWLXnIRvTFZrT9UV41kqzBO02O8vwMkL9gjz9T3kNrdXh/cL8TeA32ohzG8cSbftvINGyHMuZ8+RQFWzuBZ7l1Lt4jcnTPzWzxurwP4o5oD5ElHa0bbVFVFsaKCpPi/r/e8cipr7ArpN50h76SV5PGdwg+FqKYc40KCr44Zmc/yQxUo9bKkh2auzTt2VNJaob+RDL/Bg9uZ5ig1gZnttFzlnVYxkIRPVsbzYlKMXyz0twZkvwtYOxyOWWHDsGyOcOB04TiNu5bABgPWXi/emvUkHrRS4CR6DNaG7GBhWaLP7EewCtoKlODQ4RNS/ybKJKV56XBs5/MSlAFP8qYQKl3uBRTpj1aTa32nH/QGcyICUJINAi4QJWAJih1Zm+CtMrm2wHqA/+WQlZfAzBs2ZgcyU/wL1PokYGpGpPZPYBhcg3p9Rek4uEHqxOmUHnmxQfAAlXUJYcbjyCYjoUNcFM+Xo+BYdd0xdTgGC0rooznAWe2bCj/+Hx/2O4oTRnbRPnnCq3kmZe1dkiz+wXNr0OExrOPTOeIv1hlxNaIt/uGo/OiFCL3JBurs+sEb3307RwclyO0Ml0fhPl15Ob4Smv4=
